# %nameplates_conditional_{0}%
# custom conditions for your text, make it easier to display different content according to the requirement you set
conditional-text:
  # This is just an example that not actually enabled
  # It would display the region name with black background if you are in a region. Otherwise it would return nothing
  region:
    priority_1:
      text: '%nameplates_background_region%'
      conditions:
        papi-condition:
          condition_1:
            type: '!='
            papi: '%worldguard_region%'
            value: ""
    priority_2:
      text: ''
  # It's actually using the same method as the region example above!
  prefix:
    priority_1:
      text: '%nameplates_background_prefix%'
      conditions:
        papi-condition:
          condition_1:
            type: '!='
            papi: '%vault_prefix%'
            value: ""
    priority_2:
      text: ''
  # A weather example which is using weather conditions
  weather:
    priority_1:
      text: 'Sun'
      conditions:
        weather:
          - clear
    priority_2:
      text: 'Rain'
      conditions:
        weather:
          - rain
    priority_3:
      text: 'Thunder'
      conditions:
        weather:
          - thunder
    priority_4:
      text: 'Rainstorm'
      conditions:
        weather:
          - rainstorm
  # Plugin would hide the stamina bar when players are in water, so the two bars would not overlap
  stamina:
    priority_1:
      text: '%nameplates_offset_98%%nameplates_vanilla_stamina_hud%%nameplates_offset_-179%'
      conditions:
        papi-condition:
          condition_1:
            type: '=='
            papi: '%player_remaining_air%'
            value: "300"
    priority_2:
      text: ''
  # It would keep the income action message in the middle
  income_actionbar:
    priority_1:
      text: '%nameplates_offset_-180%%nameplates_static_income_actionbar%'
      conditions:
        papi-condition:
          condition_1:
            type: '!='
            papi: '%nameplates_actionbar%'
            value: ""
    priority_2:
      text: ''

# %nameplates_nameplate_{0}%
# This placeholder would surround the text with a nameplate
nameplate-text:
  halloween:
    nameplate: halloween
    text: '<gradient:#FFD700:#FFA500:#FFD700>Today is Halloween! Trick or treat!</gradient>'

# %nameplates_background_{0}%
# This placeholder would surround the text with a background
background-text:
  prefix:
    background: bedrock_1
    text: '%vault_prefix% %nameplates_descent_player%'
    remove-shadow: true
  position:
    background: bedrock_1
    text: '<#FFFEFD>%nameplates_image_compass%</#FFFEFD> %nameplates_descent_position%'
    remove-shadow: true
  time:
    background: bedrock_1
    text: '<#FFFEFD>%nameplates_image_clock%</#FFFEFD> %nameplates_descent_time%'
    remove-shadow: true
  weather:
    background: bedrock_1
    text: '<#FFFEFD>%nameplates_image_weather%</#FFFEFD> %nameplates_descent_weather%'
    remove-shadow: true
  hello:
    background: bedrock_1
    text: '<#FFFEFD>%nameplates_image_bubble%</#FFFEFD> %nameplates_unicode_hello%'
    remove-shadow: true
  region:
    background: bedrock_1
    text: '<#FFFEFD>%nameplates_image_compass%</#FFFEFD> %nameplates_descent_region%'
    remove-shadow: true
  update:
    background: bedrock_2
    text: '<#FFFEFD>%nameplates_image_bell%</#FFFEFD> %nameplates_descent_update%'
    remove-shadow: true

# %nameplates_static_{0}%
# Plugin would generate offset images to keep the text at a certain position regardless of the length
# So the text would be fixed at a certain place, so it's called "static-text"
# We often use this feature to create money hud or receive income actionbar sent by other plugins
static-text:
  money_hud:
    # left/right/middle
    position: right
    text: '<#FFFEFD>%nameplates_image_coin%</#FFFEFD> %nameplates_descent_money%'
    value: 180
  income_actionbar:
    # It might be a good idea if you set the actionbar position from middle to side
    position: middle
    # remove the font tag if you want to use minecraft:default font
    text: "<font:nameplates:unicode_ascent_8>%nameplates_actionbar%</font>"
    value: 180

# %nameplates_descent_{0}%
# If the character can't show correctly here, use descent-unicode instead
# Never put an image inside this section unless you surround your image with "<font:namespace:font> </font>"
# For example ItemsAdder, you should use <font:minecraft:default>%img_xxx%</font>
# Note: If you want to make an image lower, edit the y position/ascent in that plugin instead of
# using descent text or descent unicode because they are designed for characters
descent-text:
  player:
    text: "%player_name%"
    descent: 5
  position:
    text: "Your Position: %player_x%, %player_y%, %player_z%"
    descent: 5
  time:
    text: "Time: %nameplates_time%"
    descent: 5
  weather:
    text: "Weather: %nameplates_conditional_weather%"
    descent: 5
  region:
    text: "Region: %worldguard_region%"
    descent: 5
  update:
    text: "A newer version of CustomNameplates is available!"
    descent: 3
  money:
    text: "%vault_eco_balance%"
    descent: 13

# %nameplates_unicode_{0}%
descent-unicode:
  normal:
    text: "Just for registering"
    descent: 0
  hello:
    text: "Hello 여보세요 你好 こんにちは"
    descent: 5

# %nameplates_vanilla_{0}%
# This is useful for creating a vanilla like hud
vanilla-hud:
  stamina_hud:
    reverse: true
    images:
      empty: "%nameplates_image_stamina_0%"
      half: "%nameplates_image_stamina_1%"
      full: "%nameplates_image_stamina_2%"
    placeholder:
      # value/max-value can be placeholders
      value: '1.1'
      max-value: '2'