name: CustomNameplates
version: '${version}'
main: net.momirealms.customnameplates.paper.CustomNameplatesPluginImpl
api-version: 1.17
authors: [ XiaoMoMi ]
folia-supported: true
depend: [ ProtocolLib ,PlaceholderAPI ]
softdepend: [ MagicCosmetics, TAB, CMI, TrChat, ItemsAdder, Oraxen ]
permissions:
  nameplates.command.*:
    description: Gives access to all nameplate user commands
    children:
      nameplates.command.equip: true
      nameplates.command.unequip: true
      nameplates.command.preview: true
      nameplates.command.list: true
  nameplates.command.equip:
    default: true
  nameplates.command.unequip:
    default: true
  nameplates.command.preview:
    default: true
  nameplates.command.list:
    default: true
  customnameplates.admin:
    default: op
  bubbles.command.*:
    description: Gives access to bubble all user commands
    children:
      bubbles.equip: true
      bubbles.unequip: true
      bubbles.list: true
  bubbles.command.equip:
    default: true
  bubbles.command.unequip:
    default: true
  bubbles.command.list:
    default: true
  bubbles.use:
    default: true